name: Deploy to Amazon Linux EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to Amazon Linux EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}

          script: |
            set -e

            echo "===== Starting Deployment ====="

            cd /home/ec2-user/testing

            echo "Updating code..."
            git fetch origin
            git reset --hard origin/main

            echo "Stopping old container..."
            docker stop testing-my-node-app || true

            echo "Removing old container..."
            docker rm testing-my-node-app || true

            echo "Removing old image..."
            docker rmi testing-my-node-app:latest || true

            echo "Building new image..."
            docker build -t testing-my-node-app:latest .

            echo "Starting container..."
            docker run -d \
              --name testing-my-node-app \
              --restart unless-stopped \
              -p 3005:3005 \
              testing-my-node-app:latest

            echo "Cleaning unused images..."
            docker image prune -f

            echo "===== Deployment Successful ====="
