script: |
  set -e

  cd /home/ec2-user/testing

  git fetch origin
  git reset --hard origin/main

  docker compose down

  docker compose build --no-cache

  docker compose up -d

  docker image prune -f

  echo "Deployment Successful"
